/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chart;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Sylwik
 */
public class ColoursAndFont extends javax.swing.JFrame {
 Color groundColour=Color.CYAN;
 Color series1Colour=Color.RED;
 Color series2Colour=Color.GREEN;
 int font;
 int size;
 int boldItalic;
 String fontName;
 MainFrame mainFrame;
 
    public ColoursAndFont(MainFrame mainFrame) {
        super("Colours and Font");
        this.mainFrame=mainFrame;
        groundColour=mainFrame.groundColour;
        series1Colour=mainFrame.series1colour;
        series2Colour=mainFrame.series2colour;
        font=mainFrame.font;
        size=mainFrame.size;
        boldItalic=mainFrame.boldItalic;
      
        initComponents();
        MyinitComponents();
        javax.swing.border.Border border=BorderFactory.createLineBorder(Color.GRAY);
        pPanelFont.setBorder(border);
        pPanelColour.setBorder(border);
        setResizable(false);
        setAlwaysOnTop(true);
    }
    
    public void MyinitComponents() {
          cbfont.removeAllItems();
          cbboldItalic.removeAllItems();
          sfontSize.setValue(10);
          cbfont.addItem("Arial");
          cbfont.addItem("Book Antiqua");
          cbfont.addItem("Bookman Old Style");
          cbfont.addItem("Calibri");
          cbfont.addItem("Cambria");
          cbfont.addItem("Chiller");
          cbfont.addItem("Comic Sans MS");
          cbfont.addItem("Consolas");
          cbfont.addItem("Dialog");
          cbfont.addItem("Forte");
          cbfont.addItem("Gigi");
          cbfont.addItem("Jokerman");
          cbfont.addItem("Mistral");
          cbfont.addItem("Monotype Corsiva");
          cbfont.addItem("Papyrus");
          cbfont.addItem("Tahoma");

            cbboldItalic.addItem("Plain");
            cbboldItalic.addItem("Bold");
            cbboldItalic.addItem("Italic");

            cbfont.setSelectedIndex(0);
            cbboldItalic.setSelectedIndex(0); }

    public String getFontName(MainFrame mainFrame) {
    this.mainFrame=mainFrame;
    mainFrame.fontName=(String)cbfont.getItemAt(this.font);
    return mainFrame.fontName;  }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPanelFont = new javax.swing.JPanel();
        sfontSize = new javax.swing.JSpinner();
        beditFont = new javax.swing.JButton();
        cbboldItalic = new javax.swing.JComboBox<>();
        cbfont = new javax.swing.JComboBox<>();
        bclose = new javax.swing.JButton();
        lchangeFont = new javax.swing.JLabel();
        lsize = new javax.swing.JLabel();
        lfont = new javax.swing.JLabel();
        lbold = new javax.swing.JLabel();
        litalic = new javax.swing.JLabel();
        pPanelColour = new javax.swing.JPanel();
        ccpalette = new javax.swing.JColorChooser();
        lchangeColour = new javax.swing.JLabel();
        pPanelButton = new javax.swing.JPanel();
        bseries1Colour = new javax.swing.JButton();
        bseries2Colour = new javax.swing.JButton();
        bgroundColour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sfontSize.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        sfontSize.setMaximumSize(new java.awt.Dimension(30, 30));
        sfontSize.setMinimumSize(new java.awt.Dimension(1, 1));
        sfontSize.setValue(10);
        sfontSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sfontSizeMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sfontSizeMouseReleased(evt);
            }
        });

        beditFont.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        beditFont.setText("OK");
        beditFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditFontActionPerformed(evt);
            }
        });

        cbboldItalic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbboldItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbboldItalicActionPerformed(evt);
            }
        });

        cbfont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbfont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfontActionPerformed(evt);
            }
        });

        bclose.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        bclose.setText("Close");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        lchangeFont.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lchangeFont.setText("Change font");

        lsize.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lsize.setText("Size");

        lfont.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lfont.setText("Font");

        lbold.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lbold.setText("Bold");

        litalic.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        litalic.setText("Italic");

        javax.swing.GroupLayout pPanelFontLayout = new javax.swing.GroupLayout(pPanelFont);
        pPanelFont.setLayout(pPanelFontLayout);
        pPanelFontLayout.setHorizontalGroup(
            pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPanelFontLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPanelFontLayout.createSequentialGroup()
                        .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lfont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(litalic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbfont, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbboldItalic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pPanelFontLayout.createSequentialGroup()
                        .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lchangeFont)
                            .addGroup(pPanelFontLayout.createSequentialGroup()
                                .addComponent(lsize)
                                .addGap(30, 30, 30)
                                .addComponent(sfontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beditFont, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPanelFontLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bclose)
                .addGap(52, 52, 52))
        );
        pPanelFontLayout.setVerticalGroup(
            pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPanelFontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lchangeFont)
                .addGap(30, 30, 30)
                .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsize)
                    .addComponent(sfontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beditFont, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfont)
                    .addComponent(cbfont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbold)
                    .addComponent(litalic)
                    .addComponent(cbboldItalic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bclose)
                .addGap(38, 38, 38))
        );

        lchangeColour.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lchangeColour.setText("Change colour of");

        pPanelButton.setLayout(new javax.swing.BoxLayout(pPanelButton, javax.swing.BoxLayout.LINE_AXIS));

        bseries1Colour.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        bseries1Colour.setText("Series I");
        bseries1Colour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bseries1ColourActionPerformed(evt);
            }
        });
        pPanelButton.add(bseries1Colour);

        bseries2Colour.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        bseries2Colour.setText("Series II");
        bseries2Colour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bseries2ColourActionPerformed(evt);
            }
        });
        pPanelButton.add(bseries2Colour);

        bgroundColour.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        bgroundColour.setText("Ground");
        bgroundColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgroundColourActionPerformed(evt);
            }
        });
        pPanelButton.add(bgroundColour);

        javax.swing.GroupLayout pPanelColourLayout = new javax.swing.GroupLayout(pPanelColour);
        pPanelColour.setLayout(pPanelColourLayout);
        pPanelColourLayout.setHorizontalGroup(
            pPanelColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPanelColourLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pPanelColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPanelColourLayout.createSequentialGroup()
                        .addComponent(lchangeColour)
                        .addGap(18, 18, 18)
                        .addComponent(pPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ccpalette, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pPanelColourLayout.setVerticalGroup(
            pPanelColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPanelColourLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(pPanelColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lchangeColour)
                    .addComponent(pPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccpalette, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(pPanelColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPanelFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pPanelFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pPanelColour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bseries1ColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bseries1ColourActionPerformed
        series1Colour= ccpalette.getColor();
        mainFrame.series1colour=series1Colour;
        mainFrame.initChart();
    }//GEN-LAST:event_bseries1ColourActionPerformed

    private void bgroundColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgroundColourActionPerformed
        groundColour= ccpalette.getColor();
        mainFrame.groundColour=groundColour;
        mainFrame.initChart();
    }//GEN-LAST:event_bgroundColourActionPerformed

    private void bseries2ColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bseries2ColourActionPerformed
        series2Colour= ccpalette.getColor();
        mainFrame.series2colour=series2Colour;
        mainFrame.initChart();
    }//GEN-LAST:event_bseries2ColourActionPerformed

    private void beditFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditFontActionPerformed
        size=(Integer)sfontSize.getValue();
        mainFrame.size=size;
        mainFrame.initChart();
    }//GEN-LAST:event_beditFontActionPerformed

    private void cbfontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfontActionPerformed
        font=cbfont.getSelectedIndex();
        mainFrame.font=font;
        
         if(!mainFrame.firstRead)
        mainFrame.initChart();
    }//GEN-LAST:event_cbfontActionPerformed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        mainFrame.initChart();
        this.setVisible(false);        
    }//GEN-LAST:event_bcloseActionPerformed

    private void sfontSizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfontSizeMouseReleased
       size=(Integer)sfontSize.getValue();
        mainFrame.size=size;
        
         if(!mainFrame.firstRead)
         mainFrame.initChart();
    }//GEN-LAST:event_sfontSizeMouseReleased

    private void cbboldItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbboldItalicActionPerformed
        boldItalic=cbboldItalic.getSelectedIndex();
        mainFrame.boldItalic=boldItalic;
        
         if(!mainFrame.firstRead)
         mainFrame.initChart();
    }//GEN-LAST:event_cbboldItalicActionPerformed

    private void sfontSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfontSizeMouseClicked
        size=(Integer)sfontSize.getValue();
        mainFrame.size=size;
         if(!mainFrame.firstRead)
         mainFrame.initChart();
    }//GEN-LAST:event_sfontSizeMouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclose;
    private javax.swing.JButton beditFont;
    private javax.swing.JButton bgroundColour;
    private javax.swing.JButton bseries1Colour;
    private javax.swing.JButton bseries2Colour;
    private javax.swing.JComboBox<String> cbboldItalic;
    private javax.swing.JComboBox<String> cbfont;
    private javax.swing.JColorChooser ccpalette;
    private javax.swing.JLabel lbold;
    private javax.swing.JLabel lchangeColour;
    private javax.swing.JLabel lchangeFont;
    private javax.swing.JLabel lfont;
    private javax.swing.JLabel litalic;
    private javax.swing.JLabel lsize;
    private javax.swing.JPanel pPanelButton;
    private javax.swing.JPanel pPanelColour;
    private javax.swing.JPanel pPanelFont;
    private javax.swing.JSpinner sfontSize;
    // End of variables declaration//GEN-END:variables
}
